# This workflow will build a Java project with Gradle whenever a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/publishing-java-packages-with-gradle

name: Publish package to GitHub Packages
on:
  release:
    types: [created, edited, deleted, published, prereleased]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Chmod Gradle wrapper
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Publish package
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}